
# from https://github.com/travis-ci/travis-ci/issues/9831
language: python
python: "3.7"
dist: xenial
sudo: true

script:
  - python setup.py install
  - python setup.py test
  - python setup.py sdist bdist
  