
# from https://github.com/travis-ci/travis-ci/issues/9831
language: python
python: "3.7"
dist: xenial
sudo: true

install:
  - sudo apt-get install -y python-scipy

script:
  - pip install .
  - python setup.py test
  - python setup.py sdist bdist
  